name: Build Branch

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86
    - uses: actions/checkout@master
    - name: MSBuild
      run: msbuild /t:BH:Rebuild /p:Configuration=Release /p:SHA=${GITHUB_SHA::7} BH.sln
    - uses: actions/upload-artifact@v4
      with:
        name: BH.dll
        path: Release/BH.dll